// ignore_for_file: unnecessary_this


//Products = ProductModel
//Autogenerated = Product
class Product {
  List<ProductModel>? products;

  Product({this.products});

  Product.fromJson(Map<String, dynamic> json) {
    if (json['products'] != null) {
      products = <ProductModel>[];
      json['products'].forEach((v) {
        products!.add(ProductModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.products != null) {
      data['products'] = this.products!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ProductModel {
  String? category;
  String? description;
  int? id;
  List<Imgs>? imgs;
  String? name;
  int? price;

  ProductModel(
      {this.category,
      this.description,
      this.id,
      this.imgs,
      this.name,
      this.price});

  ProductModel.fromJson(Map<String, dynamic> json) {
    category = json['category'];
    description = json['description'];
    id = json['id'];
    if (json['imgs'] != null) {
      imgs = <Imgs>[];
      json['imgs'].forEach((v) {
        imgs!.add(Imgs.fromJson(v));
      });
    }
    name = json['name'];
    price = json['price'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['category'] = this.category;
    data['description'] = this.description;
    data['id'] = this.id;
    if (this.imgs != null) {
      data['imgs'] = this.imgs!.map((v) => v.toJson()).toList();
    }
    data['name'] = this.name;
    data['price'] = this.price;
    return data;
  }
}

class Imgs {
  String? imgURL;

  Imgs({this.imgURL});

  Imgs.fromJson(Map<String, dynamic> json) {
    imgURL = json['imgURL'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['imgURL'] = this.imgURL;
    return data;
  }
}
